export const QUALITY_LEVELS = ["low", "medium", "high"];

export const WORLD_CONFIG = {
  worldRadius: 88,
  eyeHeight: 1.72,
  baseFov: 72,
  interactDistance: 7.25,
  playerRadius: 0.92,
  turnSpeed: 1.55,
  lookSpeed: 1.15,
  initialPitch: -0.08,
  spawn: {
    x: 0,
    z: 28,
  },
};

export const QUALITY_PROFILES = {
  low: {
    desktopPixelRatio: 1,
    mobilePixelRatio: 0.8,
    desktopShadows: false,
    fogDensity: 0.0134,
    shadowMapSize: 0,
    textureQuality: "low",
    motionScale: 0.55,
    pulseScale: 0.55,
    ambientUpdateInterval: 1 / 24,
    lanternLights: false,
    landmarkLightScale: 0.72,
  },
  medium: {
    desktopPixelRatio: 1.35,
    mobilePixelRatio: 1,
    desktopShadows: false,
    fogDensity: 0.0125,
    shadowMapSize: 0,
    textureQuality: "medium",
    motionScale: 0.78,
    pulseScale: 0.82,
    ambientUpdateInterval: 1 / 30,
    lanternLights: true,
    landmarkLightScale: 0.88,
  },
  high: {
    desktopPixelRatio: 1.85,
    mobilePixelRatio: 1.2,
    desktopShadows: true,
    fogDensity: 0.012,
    shadowMapSize: 1536,
    textureQuality: "high",
    motionScale: 1,
    pulseScale: 1,
    ambientUpdateInterval: 0,
    lanternLights: true,
    landmarkLightScale: 1,
  },
};

export const RUNTIME_CONFIG = {
  maxFrameDelta: 0.05,
  debugSampleInterval: 0.25,
  interactionRefreshInterval: {
    touch: 0.12,
    desktop: 0.08,
  },
};

export const MOVEMENT_CONFIG = {
  walkSpeed: 5.2,
  sprintSpeed: 7.8,
  sprintBlendDamping: 5.4,
  sprintReleaseDamping: 6,
  activeVelocityDamping: 10.5,
  idleVelocityDamping: 7.2,
  groundFollowDamping: 10,
  lookClamp: 1.05,
  mouseYawFactor: 0.0021,
  mousePitchFactor: 0.00155,
  touchYawFactor: 0.0058,
  touchPitchFactor: 0.0039,
  camera: {
    bobStartThreshold: 0.04,
    bobXAmplitude: 0.014,
    bobXSprintBoost: 0.006,
    bobYAmplitude: 0.024,
    bobYSprintBoost: 0.008,
    strideWalkSpeed: 5.4,
    strideSprintSpeed: 8.8,
    stridePhaseScale: 0.55,
    bobXDamping: 12,
    bobYDamping: 12,
    rollDamping: 9,
    fovDamping: 6,
    sprintFovBoost: 1.2,
    strafeRollFactor: 0.016,
    sprintRollFactor: 0.004,
    maxRoll: 0.024,
  },
};

export const INTERACTION_CONFIG = {
  currentTargetRangePadding: {
    active: 1.15,
    passive: 0.45,
  },
  hysteresis: {
    touch: 0.9,
    desktop: 0.6,
  },
  minAlignment: {
    touch: -0.2,
    desktop: -0.05,
  },
  desiredAlignment: {
    touch: 0.15,
    desktop: 0.5,
  },
  penaltyScale: {
    touch: 3.2,
    desktop: 5.2,
  },
  currentTargetScoreBonus: 0.3,
};

export const STARTUP_VALIDATION_CONFIG = {
  requiredDomRefs: [
    "body",
    "canvas",
    "brandEyebrow",
    "brandTitle",
    "zoneName",
    "zoneDistance",
    "pointerToggle",
    "portfolioToggle",
    "pointerHint",
    "fallbackCta",
    "fallbackCtaEyebrow",
    "fallbackCtaTitle",
    "fallbackCtaBody",
    "fallbackCtaActions",
    "settingsToggle",
    "settingsPanel",
    "settingsEyebrow",
    "settingsTitle",
    "settingsClose",
    "settingsNote",
    "reducedMotionLabel",
    "reducedMotionDescription",
    "reducedMotionToggle",
    "sensitivityLabel",
    "sensitivityOptions",
    "graphicsLabel",
    "graphicsOptions",
    "introPanel",
    "introEyebrow",
    "introTitle",
    "introBody",
    "introGrid",
    "introActions",
    "fallbackPanel",
    "fallbackStatus",
    "fallbackClose",
    "fallbackHeroEyebrow",
    "fallbackHeroTitle",
    "fallbackHeroKicker",
    "fallbackHeroBody",
    "fallbackHeroActions",
    "fallbackSections",
    "inspectPanel",
    "inspectZone",
    "inspectTitle",
    "inspectKicker",
    "inspectBody",
    "inspectBullets",
    "inspectActions",
    "inspectPrompt",
    "promptEyebrow",
    "promptTitle",
    "promptHint",
    "controlsEyebrow",
    "controlsCopy",
    "debugPanel",
    "debugTitle",
    "debugFps",
    "debugQuality",
    "debugDraws",
    "debugTriangles",
    "crosshair",
    "mobileInspect",
    "mobileSprintLabel",
    "mobileInspectLabel",
  ],
  requiredAssets: [
    { path: ["headshot"], label: "Headshot texture" },
    { path: ["badges", "cloud"], label: "AWS Cloud Practitioner badge" },
    { path: ["badges", "architect"], label: "AWS Solutions Architect badge" },
  ],
  supportedExhibitTypes: ["portrait", "grove", "sanctum", "project", "portal"],
  requiredExhibitFields: [
    "id",
    "type",
    "zone",
    "title",
    "kicker",
    "body",
    "position.x",
    "position.z",
  ],
  requiredLandmarkIds: ["about", "skills", "focus", "certifications", "contact"],
  defaultExhibitAccent: "#f4dca9",
  defaultColliderRadius: 4.8,
};
